### PR TITLE
my pull request

### PR DESCRIPTION
**Pull request by julijapantitova**
comment

### CODE REVIEW

**Comment by DimaShherbina** [comment]
Please add us as reviewers :)
my pull request by julijapantitova pull request 8 olegsverdlov_murqagit - google chrome 2017-07-19 10 54 11

**Comment by OlegSverdlov** [comment]
I see no changes have been made, so it's ok to merge this nothing into master.

**Review by OlegSverdlov — CHANGES_REQUESTED** [review]
Please commit some changes! )

**Comment by julijapantitova** [comment]
juli.txt was changed

**Comment by julijapantitova** [comment]
juli.txt was changed

**Pull request merged**
